import * as directives from "./directives";
import Vue from "vue";
import { swiper, swiperSlide } from "vue-awesome-swiper";

import ActivityBlock2 from "./components/activity-block";
import ActivityChart2 from "./components/activity-chart";
import Button2 from "./components/buttons";
import AddFriendsPopup2 from "./components/add-friends";
import AnnouncementPopup2 from "./components/announcement-popup";
import ArrayView2 from "./components/json-editor/array-view";
import AssetPopup2 from "./components/asset-overview-popup";
import AssetsGrid2 from "./components/assets-grid";
import AssetsImporter2 from "./components/asset-importer";
import AssetsList2 from "./components/assets-list-item/featured-list";
import AssetsListDetail2 from "./components/assets-list-item";
import AssetsPreview2 from "./components/asset/preview";
import AssetsStoreCard2 from "./components/asset/store-card";
import Author2 from "./components/author";
import Badges2 from "./components/project/badges";
import Banner2 from "./components/banner";
import BasicPopup2 from "./components/popups/basic";
import Benchmark2 from "./components/benchmark";
import Block2 from "./components/block";
import BlockWithIcon2 from "./components/block/with-icon";
import Breadcrumb2 from "./components/breadcrumb";
import BrokenPage2 from "./components/broken-page";
import BrowserUi2 from "./components/browser-ui";
import ButtonFav2 from "./components/buttons/favorite";
import ButtonArrows2 from "./components/buttons/arrows";
import Card2 from "./components/project/card";
import Carousel3d2 from "./components/carousel-3d";
import Chat2 from "./components/chat/chat";
import ChatAnswer2 from "./components/chat-new/answer-field/field";
import ChatBase2 from "./components/chat-new/base";
import ChatGroup2 from "./components/chat-new/content/group";
import ChatGroupSidebar2 from "./components/chat-new/content/group-list";
import ChatMessage2 from "./components/chat-new/message";
import ChatMessageSmall2 from "./components/chat-new/message-small";
import ChatUser2 from "./components/chat-new/user";
import Checkbox2 from "./components/checkbox";
import CheckboxGroup2 from "./components/checkbox/group";
import Claim2 from "./components/curator-panel/claim";
import Clock2 from "./components/clock";
import CollectionItem2 from "./components/collection/item";
import CollectionList2 from "./components/collection/list";
import CommunitySpotlight2 from "./components/community-spotlight";
import ContributeForm2 from "./components/contribute/form";
import ContributePledge2 from "./components/contribute/pledge";
import ContributorBox2 from "./components/contributor-box";
import CookiePolicy2 from "./components/cookie-policy";
import CuratorInfo2 from "./components/curator-panel/info-card";
import CuratorPanel2 from "./components/curator-panel";
import CuratorReview2 from "./components/curator-review";
import CuratorsReviews2 from "./components/curator-reviews";
import CurrencyDropdown2 from "./components/dropdown-menu/currency";
import CustomModal2 from "./components/modal/custom";
import DecentralizationMeter2 from "./components/decentralization-meter";
import DottedList2 from "./components/list/dots";
import DraggableVideo2 from "./components/draggable-video";
import Dropdown2 from "./components/dropdown-menu/type-2";
import Dropdown42 from "./components/dropdown-menu/type-4";
import DropdownCurrency2 from "./components/dropdown-menu/currency";
import DropdownCustom2 from "./components/dropdown-menu/type-3";
import DropdownLang2 from "./components/dropdown-menu/language";
import DropdownMenu2 from "./components/dropdown-menu/type-2";
import DropdownPost2 from "./components/dropdown-menu";
import Emoji2 from "./components/emoji";
import EmojiSingle2 from "./components/emoji/single";
import ExchangeBar2 from "./components/exchange-bar";
import FTradedAssets2 from "./components/frequently-traded-assets";
import GameCard2 from "./components/game-card";
import GameDescription2 from "./components/game-series/game-description";
import GameIncludesItem2 from "./components/game-series/game-includes-item";
import GameIncludesList2 from "./components/game-series/game-includes-list";
import GameInstallerModal2 from "./components/game-installer";
import GamePlan2 from "./components/game-plans/plan";
import GameSeries2 from "./components/game-series";
import GamesExplorer2 from "./components/games-explorer";
import GamesGrid2 from "./components/game-grid/with-description";
import GamesGridSimple2 from "./components/game-grid/simple";
import Giphy2 from "./components/giphy";
import GlobalSearch2 from "./components/global-search";
import Guide2 from "./components/guide";
import HeadingBar2 from "./components/heading-bar";
import HeadingBarWithAdditionalAction2 from "./components/heading-bar/additional-action";
import HeadingBarWithSimpleColor2 from "./components/heading-bar/simple-colored";
import Icon2 from "./components/icon";
import ImagesExplorer2 from "./components/images-explorer";
import Img2 from "./components/img";
import Input2 from "./components/inputs";
import InputSearcher2 from "./components/inputs/searcher";
import JoinCommunity2 from "./components/join-community";
import JsonView2 from "./components/json-editor/json-view";
import Landing2 from "./components/landing";
import LandingBenefactor2 from "./components/landing/block-content/benefactor";
import LandingBlockContentLevel2 from "./components/landing/block-content/level";
import LandingBlockContentWithFeatureItem2 from "./components/landing/block-content/feature-item";
import LandingBlockTitle2 from "./components/landing/block-title/simple";
import LandingBlockTitleGradient2 from "./components/landing/block-title/gradient";
import LandingBlockTitleShadow2 from "./components/landing/block-title/shadow";
import LandingContent2 from "./components/landing/block-content/simple";
import LandingDivider2 from "./components/landing/block-content/divider";
import LandingLevel2 from "./components/landing/block-content/level";
import LandingRewardList2 from "./components/landing/block-content/reward-list";
import LandingTab2 from "./components/landing/block-content/tab";
import LandingTabs2 from "./components/landing/block-content/tabs";
import LandingTitle2 from "./components/landing/block-title/simple";
import LandingTitleGradient2 from "./components/landing/block-title/gradient";
import LandingTitleShadow2 from "./components/landing/block-title/shadow";
import LanguageSupport2 from "./components/product-overview/language-support";
import LineChart2 from "./components/charts/line";
import LoadMore2 from "./components/buttons/load-more";
import LoadingCircle2 from "./components/loading-bar/circle";
import LoadingIndicator2 from "./components/loading-indicator";
import LoadingLine2 from "./components/loading-bar";
import LogoLoader2 from "./components/loading-bar/logo-loader";
import MetroGrid2 from "./components/metro/grid";
import MetroItem2 from "./components/metro/metro-item";
import MetroTile2 from "./components/metro/metro-tile";
import Milestone2 from "./components/project/milestone";
import MilestonesLine2 from "./components/milestones-line";
import Modal2 from "./components/modal/";
import MoneyInfo2 from "./components/money-info";
import NewsArticle2 from "./components/news-list/article";
import NewsList2 from "./components/news-list/articles";
import NewsListNav2 from "./components/news-list/navigation";
import Notification2 from "./components/notification";
import NotificationInline2 from "./components/notification/inline";
import Pagination2 from "./components/pagination/index";
import ParticipationTier2 from "./components/participation-tier";

export const Swiper = swiper;
export const SwiperSlide = swiperSlide;

export const ActivityBlock = ActivityBlock2;
export const ActivityChart = ActivityChart2;
export const AddCollectionPopup = null;
export const AddFriendsPopup = AddFriendsPopup2;
export const AnnouncementPopup = AnnouncementPopup2;
export const ArrayView = ArrayView2;
export const AssetPopup = AssetPopup2;
export const AssetsGrid = AssetsGrid2;
export const AssetsImporter = AssetsImporter2;
export const AssetsList = AssetsList2;
export const AssetsListDetail = AssetsListDetail2;
export const AssetsPreview = AssetsPreview2;
export const AssetsStoreCard = AssetsStoreCard2;
export const Author = Author2;
export const Badges = Badges2;
export const Banner = Banner2;
export const BasicPopup = BasicPopup2;
export const Benchmark = Benchmark2;
export const Block = Block2;
export const BlockWithIcon = BlockWithIcon2;
export const Breadcrumb = Breadcrumb2;
export const BrokenPage = BrokenPage2;
export const BrowserUi = BrowserUi2;
export const Button = Button2;
export const ButtonFav = ButtonFav2;
export const ButtonArrows = ButtonArrows2;
export const Buttons = Button2;
export const Card = Card2;
export const Carousel3d = Carousel3d2;
export const Chat = Chat2;
export const ChatAnswer = ChatAnswer2;
export const ChatBase = ChatBase2;
export const ChatFriendsList = null;
export const ChatGroup = ChatGroup2;
export const ChatGroupNew = null;
export const ChatGroupSidebar = ChatGroupSidebar2;
export const ChatGroupWelcome = null;
export const ChatMessage = ChatMessage2;
export const ChatMessageSmall = ChatMessageSmall2;
export const ChatPrivate = null;
export const ChatUser = ChatUser2;
export const Checkbox = Checkbox2;
export const CheckboxGroup = CheckboxGroup2;
export const Claim = Claim2;
export const Clock = Clock2;
export const CollectionItem = CollectionItem2;
export const CollectionList = CollectionList2;
export const CommunitySpotlight = CommunitySpotlight2;
export const ContentNavigation = null;
export const ContributeForm = ContributeForm2;
export const ContributePledge = ContributePledge2;
export const ContributorBox = ContributorBox2;
export const CookiePolicy = CookiePolicy2;
export const CuratorInfo = CuratorInfo2;
export const CuratorPanel = CuratorPanel2;
export const CuratorReview = CuratorReview2;
export const CuratorReviews = null;
export const CuratorsReviews = CuratorsReviews2;
export const CurrencyDropdown = CurrencyDropdown2;
export const CustomModal = CustomModal2;
export const DecentralizationMeter = DecentralizationMeter2;
export const DottedList = DottedList2;
export const DraggableVideo = DraggableVideo2;
export const Dropdown = Dropdown2;
export const Dropdown4 = Dropdown42;
export const DropdownCurrency = DropdownCurrency2;
export const DropdownCustom = DropdownCustom2;
export const DropdownLang = DropdownLang2;
export const DropdownMenu = DropdownMenu2;
export const DropdownPost = DropdownPost2;
export const Emoji = Emoji2;
export const EmojiSingle = EmojiSingle2;
export const ExchangeBar = ExchangeBar2;
export const FTradedAssets = FTradedAssets2;
export const GameCard = GameCard2;
export const GameDescription = GameDescription2;
export const GameIncludesItem = GameIncludesItem2;
export const GameIncludesList = GameIncludesList2;
export const GameInstaller = null;
export const GameInstallerModal = GameInstallerModal2;
export const GameLibraryCard = null;
export const GamePlan = GamePlan2;
export const GameSeries = GameSeries2;
export const GamesExplorer = GamesExplorer2;
export const GamesGrid = GamesGrid2;
export const GamesGridSimple = GamesGridSimple2;
export const GamesList = null;
export const Giphy = Giphy2;
export const GlobalSearch = GlobalSearch2;
export const Guide = Guide2;
export const HeadingBar = HeadingBar2;
export const HeadingBarWithAdditionalAction = HeadingBarWithAdditionalAction2;
export const HeadingBarWithSimpleColor = HeadingBarWithSimpleColor2;
export const Icon = Icon2;
export const ImagesExplorer = ImagesExplorer2;
export const Img = Img2;
export const Input = Input2;
export const InputSearcher = InputSearcher2;
export const JoinCommunity = JoinCommunity2;
export const JsonView = JsonView2;
export const Landing = Landing2;
export const LandingBenefactor = LandingBenefactor2;
export const LandingBlock = null;
export const LandingBlockContentLevel = LandingBlockContentLevel2;
export const LandingBlockContentWithFeatureItem =
  LandingBlockContentWithFeatureItem2;
export const LandingBlockTitle = LandingBlockTitle2;
export const LandingBlockTitleGradient = LandingBlockTitleGradient2;
export const LandingBlockTitleShadow = LandingBlockTitleShadow2;
export const LandingButton = null;
export const LandingContent = LandingContent2;
export const LandingDivider = LandingDivider2;
export const LandingFeatureItem = null;
export const LandingGradientBlock = null;
export const LandingLevel = LandingLevel2;
export const LandingRewardList = LandingRewardList2;
export const LandingSlider = null;
export const LandingTab = LandingTab2;
export const LandingTabs = LandingTabs2;
export const LandingTitle = LandingTitle2;
export const LandingTitleGradient = LandingTitleGradient2;
export const LandingTitleShadow = LandingTitleShadow2;
export const LanguageSupport = LanguageSupport2;
export const LanguagesDropdown = null;
export const LineChart = LineChart2;
export const LoadMore = LoadMore2;
export const LoadingCircle = LoadingCircle2;
export const LoadingIndicator = LoadingIndicator2;
export const LoadingLine = LoadingLine2;
export const LogoLoader = LogoLoader2;
export const MetroGrid = MetroGrid2;
export const MetroItem = MetroItem2;
export const MetroTile = MetroTile2;
export const Milestone = Milestone2;
export const MilestonesLine = MilestonesLine2;
export const Modal = Modal2;
export const ModalList = null;
export const MoneyInfo = MoneyInfo2;
export const NewsArticle = NewsArticle2;
export const NewsList = NewsList2;
export const NewsListNav = NewsListNav2;
export const NewsListNavigation = null;
export const Notification = Notification2;
export const NotificationInline = NotificationInline2;
export const OptionBlock = null;
export const Pagination = Pagination2;
export const ParticipationTier = ParticipationTier2;
